### ISSUE TITLE
Embedding ... ?

### ISSUE THREAD

**Issue by nfreear** [IET-OU/our-journey#17]
Hi @TimCoughlan,

Another idea ... !

I'm thinking particularly for dissemination, blogging, etc. (_... e.g. for a funding drive!_)

It may be worth giving a little thought to the potential for a simple embed via an `<iframe>`. This is often facilitated via a URL parameter, for example `?embed=true` (which can in turn set a `class` on the body via Javascript). Some thoughts:

 * You/ we may decide to, for example, hide the editor by default in embedded mode;
 * We can minimise or remove margins around the page;
 * Possibly scale logos;
 * I've just come across a really interesting CSS property, `zoom`, which appears to affect the whole page ([CSS tricks](https://css-tricks.com/almanac/properties/z/zoom/)).

_(We don't have to do all of the above initially, just things to consider.)_

Yours,

Nick

---
### Example HTML

Here's an example embedding snippet:

```html
<iframe
  class="our-journey-iframe"
  style="height: 500px; max-width: 1240px; min-width: 680px; width: 100%;"
  allowfullscreen
  src="https://iet-ou.github.io/our-journey/?demo=1&embed=true&zoom=0.7"
>
</iframe>
```

### Example CSS

And some possible CSS styles:

```css
body.embed-mode {
  font-size: 1.2rem; /* Compensate for the zoom! */
  margin: 0;
  zoom: 70%;
}

.embed-mode #editor {
  display: none;
}

.embed-mode .footer-logos img {
  height: 50px;
}

...
```
