### ISSUE TITLE
Navigation accessibility — landmark roles, "listitem" role

### ISSUE THREAD

**Issue by nfreear** [IET-OU/our-journey#20]
Hi @TimCoughlan,

You / we may want to employ [landmark roles](https://w3.org/TR/wai-aria-1.1/#landmark_roles), and for example, `role=listitem` to improve semantics.

Ta,

Nick

---

HTML / SVG:

```html
<div role="main">

  <svg role="list" ...>

    <svg role="listitem" class=" CARD " ...>

      <svg role="button" ...>

    ...
```

CSS:

```css
[ role = button ],
[ type = submit ]
{
    cursor: pointer;
}
```

---
## Useful reading

 * https://w3.org/TR/wai-aria-1.1/#landmark_roles
 * https://w3.org/TR/wai-aria-1.1/#listitem
 * https://w3.org/TR/wai-aria-1.1/#list
